import { PaymentStatus } from '../../database/generated/prisma/enums';

export const PAYMENT_FLOW = {
  DEFAULT_STATUS: PaymentStatus.PENDING,
  REVIEW_STATUS: PaymentStatus.UNDER_REVIEW,
  SUCCESS_STATUS: PaymentStatus.APPROVED,
  FAILURE_STATUS: PaymentStatus.FAILED
} as const;

export const PAYMENT_CODE = {
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_APPROVED: 'BOOKING_ALREADY_APPROVED',
  PAYMENT_SLIP_REQUIRED: 'PAYMENT_SLIP_REQUIRED',
  PAYMENT_ALREADY_FAILED: 'PAYMENT_ALREADY_FAILED',
  PAYMENT_ALREADY_UNDER_REVIEW: 'PAYMENT_ALREADY_UNDER_REVIEW'
} as const;

export const PAYMENT_DEFAULT = {
  DISCOUNT: 0,
  SLIP_URL: ''
} as const;
